# fly.toml app configuration file generated for ecogest-frontend
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = "ecogest-frontend"
primary_region = "scl"

[build]
  image = "ecogest-frontend:latest"

[env]
  VITE_API_URL = "https://ecogest-backend.fly.dev/api"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1

[[services]]
  protocol = "tcp"
  internal_port = 3000
  processes = ["app"]

  [services.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 850

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [services.tcp_checks]
    enabled = true
    grace_period = "1s"
    interval = "15s"
    timeout = "2s"
    grace_period = "5s"

[checks]
  [checks.status]
    type = "http"
    interval = "30s"
    timeout = "5s"
    grace_period = "5s"
    method = "get"
    path = "/"
    protocol = "http"
    success_threshold = 1
    failure_threshold = 2
